#+TITLE: Mirza Ghasmi

* Ingredients

| Ingredients | Amount | Unit        |
|-------------+--------+-------------|
| Egg plant   |      1 | piece       |
| Tomatoes    |      3 | piece       |
| Garlic      |      1 | clove       |
| Tomato pure |      1 | tea spoon   |
| Egg         |      2 | small piece |
| Salt        |        |             |
| Pepper      |        |             |
| Oil         |        |             |

* Recipe 

  Preheat an oven to a 180 degrees Celsius.
  
  Cut the egg plant i three slices length wise and again three across, and half the tomatoes. 
  Place them on a baking tray with the garlic. 

  In a small bowl mix some oil, salt, and pepper. 
  Brush the mixture over the egg plant and tomato pieces, and put them into the oven for approximately 15 minutes.
  
  When the egg plant and tomatoes are baked, take them out of the oven and remove the skin from the tomatoes. 
  Chop the tomatoes fine and preheat a pan to medium low heat. 
  Add the chopped tomatoes and garlic and smash the garlic (it should be almost like a paste). 
  When the tomatoes are bubbling add oil, let it heat back up. 
  The tomato pure and stir it through, and heat backup. 
  Chop or mash the egg plant fine and add them to the pan, let it cook together for a bit.  
  If the mixture is bitter add a splash of water. 
  
  When you have a combined mass, make a hole in the centre, add a bit of oil and crack in the two eggs let the eggs fry for a bit, and mix everything together.
  Let everything cook through for 5 minutes (or until the eggs are cooked) on the pan. 
  
* Note 

  1. The baking of the egg plant and the tomatoes can be done on a barbecue, here only cut the egg plant in half lengthwise.  
