* Pasta

*Ingredients* 

| Ingredient           |      Amount | Unit   |
|----------------------+-------------+--------|
| Tipo 00 flour        |         250 | gram   |
| Eggs                 |           3 | Pieces |
| Durum Simolina flour | For dusting |        |

*Recipe* 

Put the flour in a bowl and make a small well for the eggs.  Pour in
the eggs, do not beat the eggs before hand, use a fork to turn the
eggs to the flour slowly. When it becomes to difficult to use the fork
switch to your hands. When you have a uniform mass, turn the dough out
onto the table and knead for 10-15 minutes or until smooth, and form
it into a ball. Dust the dough ball with flour and wrap it in clean
film.  Put the wrapped dough ball into the fridge at let it rest for a
minimum of 20 minutes, though maximum 3 hours.

After the resting roll out the dough ball til you can see your fingers
through it. Cut and form it into the pasta you want. USE LOTS OF
SIMOLINA FLOUR for dusting.

Next step dry, till well dry or cook aldente. 
