* All garden soup 

*Ingredients*

The ingredients for this soup is hard to quantify as it depends on how much you want to make. 
This list is based on the first time I prepared the dish. 

/Base ingredients/

The following ingredients make for a base soup the can be enjoyed as is.

| Ingredient                | Amount       | Unit      |
|---------------------------+--------------+-----------|
| Red onions                | 5-6 (medium) | piece     |
| Celery                    | 5-6          | stalk     |
| Carrots                   | 5-6 (medium) | piece     |
| Leak                      | 1 (big)      | piece     |
| Tomato sauce              | 1-1.5        | litre     |
| Tomato pure               | 1-2          | tbls      |
| Tomatoes  (San manzana)   | 1            | pack      |
| Thyme                     | to taste     |           |
| Garlic                    | 1-2          | cloves    |
| Butternut squash          | 1 (small)    | piece     |
| Salt                      | to taste     |           |
| Pepper                    | to taste     |           |
| Balsamic Vinegar          | to taste     |           |
| Chilli powder (fire dust) | 1.5          | tea spoon |
| Basel                     | to taste     |           |
| Feta                      | 250          | gram      |
| olive oil                 |              |           |


/Meat/

You can add any meat to the soup, but if you add beef or pork I suggest also adding bacon lardons and brown off the meat well in the pot before frying the vegetables.
   

*Recipe*


You will need a big pot (5+ litres). 

/If you want to add meat and bacon:/

In a cold pot add 1-2 tbls of olive oil and add in the bacon lardons.
Turn on the heat to medium and the fat of the bacon render out and let the bacon brown, stir occasionally.

Cut meat in to bite size chunks (real bite sizes not tiny bits). 
Remove the bacon lardons from the pot. 
In batches brown the meat well on all sides.
When all meat is brown remove from the pot.
Judge the amount of left over fat from the lardons, if you judge it to much remove some.

/Vegtables/

Put two tbls of olive oil into the pot and bring it up to temperature, medium heat. 
Finely slice and dish the onions and put in the pan, cook until translucent.
Finely dice the carrots and celery and throw in with onions, cook till the celery is starting to turn translucent.
Put chilli powder and tomato pure into the bottom of the pan and "fry" it off and then mix into the dish 





Add some olive oil to the

 



