* Barbari

Barbari is a Persian bread often enjoyed in the morning with cream and honey as a breakfast item.

This is my best attempt at recreating the bread. 
This particular recipe will probably change, check the comments why

**Ingredients

*** For the bread it self

| Ingredient   | Amount | Unit  |
|--------------+--------+-------|
| Fresh Yeast  |     25 | grams |
| Bread flour  |    730 | grams |
| Salt         |      2 | tsp   |
| Water (luke) |    450 | ml    |

*** Roomal 

| Ingredient | Amount | Unit  |
|------------+--------+-------|
| Oil        |      1 | tsp   |
| Sugar      |      1 | tsp   |
| Flour      |      1 | Tblsp |
| Water      |    120 | ml    |

*** Toping (optional)

Nigella and/or sesame seeds roughly a table sp0on of each


** Recipe:

Crumple the yeast into a bowl and add the water, combine together by whisking and add the salt while you do this.
Add the flour A LITTLE AT THE TIME. It may not need it all, or you may need to neat in some (I cannot figure out if my flour brand of choice is horribly inconsistent).
neat til smooth.


Put some oil in to a bowl, for the dough to a ball and put it into the bowl.
Turn the dough to covered in oil. 
Cover the bowl with a damp tea towel and let the dough rest for 1 hour or until doubled in size, mine take less time.

After the first rise, knock the dough back and divide in two equal halves and shape them into ovals.
Put them on an oiled or parchment covered baking tray (I use the latter) and cover with a damp tea towel for second rise until double in size (45 min to an hour).

While the dough is proving, make the Roomal.
Through all the Roomal ingredients into a sauce pan, gently heat it up while you stir an until it thickens and is a uniform mass.
Take it of the head (remember to remove your stirring utilise.

Preheat the oven to 230 degrees C.

After second rise poke deep lines length wise in the bread. 
3-4 lines depending on the width of your bread. 
If you do not understand what I mean search for a picture of a barbari. 

Brush the bread with the roomal and cover it well and the cover with the seeds.

Bake for 15-18 minutes till golden brown keep and eye on it and if your own is crap (like mine) and bake uneven, turn the baking sheet 180 degrees once during baking.

Take the bread out and let it rest on a wire rack.


** Comments

This recipe is still a bit guess work due to the fact that it is adapted from a recipe originally using the empirical system.
This has caused a few issues. 

- The original recipe called for 480 grams of flour (directly translated) and 470ml of water.
  - However! Dialling down the water to 450ml still didn't get the dough described in the recipe.
  - Therefore I dialled up the flour content to first 500grams and later 730 
- This recipe would be much!!!! easier in a stand mixer. 

