* Dads White Bread

*Ingredients*

| Ingredient    | Amount | Unit        |
|---------------+--------+-------------|
| Fresh yeast   |  25-50 | gram        |
| Wheat flour   |    800 | gram        |
| Milk          |      6 | dl          |
| Salt          |      2 | table spoon |
| Sugar         |      1 | table spoon |
| Sunflower oil |     .5 | dl          |

*Recipe*

crumble up the yeast in a bowl. Heat the milk 
to body temperature. Mix the milk and the 
yeast till the yeast is dissolved. Mix in the oil,
salt, and sugar. Sieve in the flour and mix. When 
the dough is well mixed turnout onto a floured work 
surface and neat until smooth (8-15 minutes). If needed 
add a bit more flour. 

Put a way for proofing covered with a damp tea towel.
For 45 minutes. 

Turn unto a well floured surface an knock back. divide 
into two even pieces. Shape to loaves use the fold up 
technique. Place on a baking tray and cover with damp 
tea towel and let raise for 30 minutes. 

Preheat oven to 190 degrees, hot air. Bake the bread for 
20-25 minutes. (Test with a skewer if it comes out clean
the bread is done). When you take it out, if you tap it 
lightly on the bottom, it should sound hollow.

Let the bread rest for 10 minutes before tugging in. 

*REMARK 1:* The amount of yeast will affect the flavour.  

*REMARK 2:* The milk can be whole, skin, or low fat. It can 
even be replaced with water or Yogurt. /Note:/ Yogurt will
change the flavour.  
   
