* Euroman Pizza Dough Slow

Roughly dough for two pizzas

*Ingredients*

| Ingredient          | Amount | Unit        |
|---------------------+--------+-------------|
| Tipo '00' Flour     |    350 | gram        |
| Durum flour         |     50 | gram        |
| Lukewarm water      |    250 | ml          |
| yeast (fresh/dried) |   8-10 | gram        |
| fine sea salt       |   1.75 | tea spoon   |

*Recipe* 

1) Weigh out the two flours separately 
2) Stir 50 ml of the water, salt, yeast and 4 table spoons of tipo flour together as a pre-dough.
   It should be smooth
3) Cover the pre-dough with some clean wrap and let raise to twice the size in a warm place. 
   It can take between 35 minutes to and hour. 
4) Stir the rest of flour, both durum and tipo, and water together with the pre-dough
   and knead the dough thoroughly until elastic and smooth.
5) Put the dough back in the mixing bowl and cover with clean wrap. Let the dough slowly raise 
   in a cool place (5-10 degrees 'C) for 12 - 18 hours
6) Punch back the dough, divide in half, make two tight dough balls out of each half, dust with flour, 
   cover LIGHTLY with clean wrap and let raise on the table counter for 1-2 hours   

*Forming to pizza*

When you form the two dough balls to pizza. Take a doughball press down in the centre and spread 
out. Slowly use your finger to press out the dough from the centre, turn if needed but avoid 
touching the outer crust.  

*Raising tip* 

If you let the dough raise in the fridge (2-3'C) take out the dough 3-4 hours BEFORE the normal cool 
raise time and let raise on the kitchen counter. 

   
