* Flatbread - without yeast 
*Ingredients:*
| Ingredient     | Amount | Unit        |
|----------------+--------+-------------|
| Wheat flour    | 125    | gram        |
| Fine salt      | 1/2    | teaspoon    |
| Lukewarm water | 3/4    | dl          |
| Olive oil      | 1/2    | table spoon |

*Recipe* 

Sieve the flour and salt into a bowl. 
Mix water and oil in an jar/glass and 
mix into the flour till a assembled 
flip the dough out of the bowl onto 
a dry work surface and neat until smooth.
Role the dough into a ball. 
Let the dough rest for 10 - 15 minutes.

Divide dough into four small balls 
Heat a pan till it is smoking and 
turn down the heat a bit. 

Roll out one dough ball into a shape which is thin.
Put it on to the pan for 1-1.5 minute and flip. 
During the cooking time role the next bread repeat until done.

*REMARK 1:* During the cooking of the first side, 
do not press down on the bread. The bubbles forming will give 
the classic "burning marks" when flipping. After flipping 
you must pres the bread

*REMARK 2:* Crispy bread = thin roll out
