* River Cottage White bread 

*Ingredients* 

| Ingredient     | Amount | Unit    |
|----------------+--------+---------|
| Dry yeast      |     10 | gram    |
| Tempered water |    600 | ml/gram |
| Wheat flour    |      1 | kg      |
| Salt           |     20 | gram    |

*Recipe* 

Mix the flour, yeast, and salt in bowl and add the water. 
Mix until the dough releases easily from the edges of the bowl.
Let the dough out onto a work unfloured work surface, and knead 
the dough for 5 to 10 minutes, to stretch the gluten. For the dough
into a ball, lightly oil the bowl and place the dough back in and 
cover with a damp tea towel. 
Let it prove for 1 to 1.5 hours. Take the dough out onto a lightly 
floured work surfaces and knock it back. Form it back into a dough 
ball, divide the ball into two and knock both back and form each piece
of dough into a loaf. Put both on a floured cool baking tray diagonally 
of each other, cover with a damp tea towel and let it raise for a second 
time for 30-40 minutes. Preheat an oven for 220C and place the tray on the middle 
rack and back for 30 to 40 minutes. Depending on how soft you want your bread. 
Tack out of the oven onto a cooling rack FOR AT LEAST 10 Minutes before tucking in.
