* Chimichuri 

*DISCLAIMER:* This is my version of Chimnichuri sauce, I do not claim it to be traditional or anything like that!

*Ingredients* 

| Ingredient       | Amount               | Unit   |
|------------------+----------------------+--------|
| Parsely          | A LOT                |        |
| other herbs      | some                 |        |
| Red onion        | 1 (small)            | piece  |
| Garlic           | 2                    | cloves |
| Chilli           | 1-2                  | piece  |
| Olive oil        | ALOT                 |        |
| Red vine vinegar | 1/3 of the olive oil |        |
| Salt             |                      |        |
| Black pepper     |                      |        |

*Note* The amount of other herbs varies based on the amount of Parsley and the amount of Olive oil also depends on that. 
But in general I use 2DL oil per bunch of parsley and 1/3 other herbs to parsley 

*Note:* I usually go with two bunches/pots of Parsley and if possible I mix broad leaf/Italian with normal. 

*Note:* Other herbs could be sage, oregano, and coriander. 

*Recipe*

Get a bowel. 
Chop all the herbs finely with a sharp knife and put them in the bowl. 
Finely dice the chilli with seeds and the red onion and throw it in to the bowl. 
Peal and grind the garlic into the bowel. 
Add  oil and vinegar, mix and stir along the way. 
Taste to see if it needs more vinegar or oil, it will depend on both. 
Add salt and black pepper to taste. 

Cover an put into the fridge for at least! 30 minutes. 
Take out make final taste adjustments with salt, pepper, vinegar/lemon juice and use as sauce or dressing. 

** Notes 

Chimichuri is a amazing and goes well both as a salad dressing or a meat sauce, it works amazingly with Salmon, meaty fish, pork, chicken, lamb, duck, beef, deer, and goat. 

