* "Italian" Ragu

1. To avoid controversy, this is my take on Ragu bolognese.
2. This is a part based recipe and allows you to easily scale it up and down.

** Ingredients

We assume that 1 part here is 200 grams 

| Ingredient                      | Amount | Unit   |
|---------------------------------+--------+--------|
| Celery                          |      1 | part   |
| Carrot                          |      1 | part   |
| Yellow / Red onion              |      1 | part   |
| Garlic                          |    1-3 | gloves |
| Minced beef (see below)         |    1.5 | part   |
| tomato pure                     |      1 | tbls   |
| chopped tomatos                 |      1 | can    |
| Whole milk                      |    100 | ml     |
| White wine / Balsacmic vinegear |     50 | ml     |
| Salt                            |        |        |
| Peber                           |        |        |

In this version minced beef is 1.5 part, but for lasagne I would increase to 2 parts simply for bulk.  

*** Optional ingredients

| Ingredient  | Amount | Unit  |
|-------------+--------+-------|
| Mushrooms   |  1.5-3 | part  |
| Marmit      |      1 | tbls  |
| Bell pepper |    1-2 | fruit |


1. Mushrooms can, with benefit, be added to the dish either as a supplement and bulk up, or as a replacement of meat.
   - If you replace the meat with mushroom, I recommend mixing different types of mushrooms (get some meaty once beefsteak and porcupine mushrooms)
2. Marmit should be added after bowling down and before salt!
3. Bell pepper should be red, orange, or yellow. Green bell peppers are for sinners and should burn in hell.  

*** Suitable herbs to adds

- Oregano
- Basel
- Sage
- Thyme

** Recipe

Finely dice the carrots, onion, and celery and preheat a pot.
Add a couple of healthy (big) glugs of olive oil to the pan and let it warm up (this is very important).
Add the diced vegetables to the mix, sweat them until the onions turns translucent and the celery starts to become opaque.
/You have to cook it long enough for the water to evaporate from the vegetables, otherwise the next step will take forever and a day/.
Next, break up the mince and add it to the pot, stir it in an let it brown of.
It is preferable if some of the mince caramelise, it brings a nice depth to the dish.
At this stage it is also okay if some of the vegetables take some colour.

If you want to add mushrooms to the mix, add them now (chopped of course).
Let them sweat down and let the water evaporate.

Add the garlic and let it fry of just a little to remove the sharpness of the garlic. 

Next, the process so far should have taken between 30-45 minutes depending on the heat you use and the water content of your vegetables and meat. 
Now, we add the tomato pure (1 tbls for the first part after .5 tblsp per part) let it "fry" off for 2-3 minutes while you stir the content of the pot.
We do this to remove acidity.

Add the vinegar and stir into the dish and add 1 can of chopped tomatoes for each part of carrots you have added.
After you have emptied a can fill it with water and add that to the pot as well (judgement call: don't add to much water)
Stir the content of the pod and combine.

Now let the ragu cook on a low heat (simmering) for anywhere between 45 minutes and 8 hours, top up with water if need.
When you think it is done, add the milk (100 ml for each can of tomatoes), maybe you need more if the portion is big.
Let this cook in to the dish for 10-15 minutes.
The ragu should be thick not lose. 
After this add your marmit, salt, peper, and herbs to taste.

*** Recommendations

    - The ragu freezes really well, utilise that for food prepping.
    - Don't add Parmesan to the ragu, it will make it way to salty    

*** Notes

*Letting the water evaporate:* This enables us to actually fry of stuff and build flavours, such as those gained by caramelisation, into the dish making it a very rich dish.    
