* Tomato Sauce alla Lars 

*Ingredients* 

| Ingredient                        |  Amount | Unit              |
|-----------------------------------+---------+-------------------|
| (Red/White) Onions                |     300 | gram              |
| Celeriac stalks                   |     3-4 | pieces            |
| Carrots                           |     3-4 | pieces (big ones) |
| Tomato pure                       | 25 - 50 | gram              |
| San Marzano tomatoes              | 400-500 | gram              |
| San Marzano canned diced tomatoes |       2 | cans              |
| Balsamic Vinegar                  |     1-2 | table spoon       |
| Olive oil                         |         | ENOUGH            |
| Basil                             |       1 | Bunch             |
| Oregano                           |       1 | Bunch             |
| Salt                              |         | To taste          |
| Sugar                             |       1 | Nib               |
| Pepper                            |         | To Taste          |
| Water                             |     1-2 | Cans              |


*Notes:* The amount of tomato pure depends on the intensity you want. Oregano can be replaced with dry if needed. 

*Recipe* 

Preheat a pot to medium heat. Dice onions, celeriac, and carrots, keep the onions separated. 
When the pot is hot put the onions in a put a pinch of salt on stir, put the lit on and stir 
occasionally until the onions are translucent. While this happen, quarter or dice your tomatoes. 
When the onions are translucent add the vinegar, carrots and celeriac, give it a stir every 3 minutes 
for 9 minuets, keep the lit on. Remove the lit make a circle in the bottom of the pan, put the 
tomato pure in the circle and let it "roast" of. stir every thing. Add your fresh tomatoes and 
stir, let it "roast" for 4-5 minuets. Pour in the canned tomatoes, fill each can with water and 
add this as well. Give a good stir and cover with the lit. After 30 minutes, chop half the basil 
and oregano and put in stir, put the lit on and let it simmer for as long as you want /Minimum/ 1 hour. 
After simmering is done taste for bitterness/sourness, if it is either add a pinch of sugar. Add salt 
and pepper to taste. 

** Notes  

*** For Pizza 
- If you plan to use it the sauce for Pizza BLEND it first 

