#+TITLE: Roasted Beets Root Salad

* Ingredients

  | Ingredients         | Amount | Unit  |
  | Beets root          |    500 | g     |
  | Cherry tomatoes     |  10-15 | piece |
  | Spinach             |    200 | g     |
  | Feta / sheep cheese |     50 | g     |
  | Pomegranate seeds   |  10-15 | g     |
  | Olive oil           |        |       |
  | Vegetable oil       |        |       |
  | Salt                |        |       |
  | Pepper              |        |       |
  | Yogurt              |      2 | dl    |
  | dill                |        |       |

* Recipe

  Mix yogurt with dill.
  
  Preheat oven to 200 degrees.  
  Cut the beets root in to 3-5cm sticks (fries), mix with a little vegetable oil salt and pepper, and bake in the oven till done (time can vary a lot).
  Rinse a slice the spinach. 
  Bake tomatoes in oven for the remaining 5-10 minutes of the beets roots.
  Take out beets and tomatoes from the oven, and let cool for 5-10 minutes (it is a salad after all)
  Put the pomegranate seeds, spinach and cheese in a bowl and mix it lightly.
  Add the tomatoes, mix again.
  Add the beets and mix.
  Add some olive oil and give a last mix.
  Plate up and add some salt (preferably flakey for eye candy).  

  Put a dollop of the yogurt dill mix next to the salad on each plate.


* Notes

  1. This dish can be served as is, as an amazing salad or as a side to a lovely piece of salmon, beef, or chicken.
  2. If the olive oil is very rich, mix it first with a bit of lemon juice or balsamic vinegar
  
