* Roasted Pineapple Salad

*Ingredients*

| Ingredients            | Amount | Unit  |
|------------------------+--------+-------|
| Pineapple (fresh)      |      1 | piece |
| Cherry Tomatoes        |     20 | piece |
| Beef Tomatoes          |      5 | piece |
| Feta cheese            |    250 | gram  |
| Spinach                |    300 | gram  |
| Orange                 |    5-6 | piece |
| Red/Orange Bell pepper |      2 | piece |

- Beef tomatoes can be replaced by other tomatoes 
- Oranges can be any variety 

*Recipe*

Start by preheating an oven for 200 degrees Celsius.  

Half the cherry tomatoes and cut down the beef tomatoes to a similar size, put on to a oven proof tray. 
Peal and roughly dice the oranges and put them into the tray as well. 
Drizzle with oil, salt and black pepper.
Put into the oven for 30 minutes, when there is 10 minutes left of the cooking time throw in the block of feta right on top. 
Preheat a pan, preferably a griddle pan, while it heats quarter the pineapple and remove the core and skin, and slice the bell peppers in to julienne.
Place the pineapple on the pan and let it caramelise on all sides, remove and throw on the bell peppers. 
Slice the spinach into ribbons and add to a bowl. 
Chop the pineapple and add to the bowl as well 
Take out the tray from the oven and break down the feta into smaller pieces and put the full content of the tray into bowl. 
Add the bell pepers and mix. 

Dressing: Use a couple of table spoon fulls of chimichuri sauce (there is a recipe in the sauce folder). 

*Optionals*

- Add some crunch by adding either croutons or roasted pine nuts.  
- You can bulk up the salad by adding roasted rainbow roots





